

trigger:
- main

pool: 
  vmImage: 'ubuntu-latest'

steps:


- task: Maven@4
  inputs:
    mavenPomFile: '$(System.DefaultWorkingDirectory)/demo/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false




