
trigger:
- main

pool: Ubuntu Office

steps:

- script: | 
   echo "##vso[task.setvariable variable=JAVA_HOME]$(Agent.ToolsDirectory)/jdk/11.0.0"   
    displayName: 'Set JAVA_HOME'
   

  
- task: Maven@3
  inputs:
    mavenPomFile: 'demo/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
